version: '3'
services:
   web:
      restart: always
      build:
          context: ..
          dockerfile: ./deployment/Dockerfile
      image: makeuoft-site:latest
      command: gunicorn main:flask_app --bind 0.0.0.0:8181
      ports:
         - "8181:8181"
      volumes:
         - ./application:/application
         - /var/run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
      environment:
         - DB_USER_NAME=makeuoftsite
         - DB_USER_PW=wRln2SiQ6*UswiZe+Or$$
         - DB_NAME=makeuoft
         - SECRET_KEY=secret
         - DB_SERVER=localhost
