"""empty message

Revision ID: 55b5883f747b
Revises: 
Create Date: 2019-12-15 20:52:08.792538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b5883f747b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailing_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailing_list_email'), 'mailing_list', ['email'], unique=True)
    op.create_table('parts_available',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=255), nullable=False),
    sa.Column('part_manufacturer', sa.String(length=255), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('quantity_remaining', sa.Integer(), nullable=True),
    sa.Column('serial_number', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parts_available_part_manufacturer'), 'parts_available', ['part_manufacturer'], unique=False)
    op.create_index(op.f('ix_parts_available_part_name'), 'parts_available', ['part_name'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_tag_name'), 'tag', ['tag_name'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(length=5), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=True),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_team_code'), 'teams', ['team_code'], unique=False)
    op.create_table('parts_signed_out',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_returned', sa.Boolean(), nullable=True),
    sa.Column('part_healthy', sa.Boolean(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('part_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts_available.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_parts_available',
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['part_id'], ['parts_available.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'part_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('id_provided', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_name', sa.String(length=255), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('ethnicity', sa.String(length=255), nullable=False),
    sa.Column('tshirt_size', sa.String(length=5), nullable=False),
    sa.Column('dietary_restrictions', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('study_level', sa.String(length=16), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('resume_path', sa.String(length=255), nullable=False),
    sa.Column('q1_prev_hackathon', sa.Text(length=1000), nullable=False),
    sa.Column('q2_why_participate', sa.Text(length=1000), nullable=False),
    sa.Column('q3_hardware_exp', sa.Text(length=1000), nullable=False),
    sa.Column('referral_source', sa.Text(length=255), nullable=False),
    sa.Column('mlh_conduct_agree', sa.Boolean(), nullable=False),
    sa.Column('mlh_data_agree', sa.Boolean(), nullable=False),
    sa.Column('resume_sharing', sa.Boolean(), nullable=False),
    sa.Column('age_confirmation', sa.Boolean(), nullable=False),
    sa.Column('submitted_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('evaluator_id', sa.Integer(), nullable=True),
    sa.Column('evaluator_comments', sa.Text(length=255), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('interest', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tag_parts_available')
    op.drop_table('parts_signed_out')
    op.drop_index(op.f('ix_teams_team_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_tag_tag_name'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_parts_available_part_name'), table_name='parts_available')
    op.drop_index(op.f('ix_parts_available_part_manufacturer'), table_name='parts_available')
    op.drop_table('parts_available')
    op.drop_index(op.f('ix_mailing_list_email'), table_name='mailing_list')
    op.drop_table('mailing_list')
    # ### end Alembic commands ###
