"""empty message

Revision ID: 60051975b8df
Revises: 01fab3a7cf0f
Create Date: 2020-01-15 20:28:46.422784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60051975b8df'
down_revision = '01fab3a7cf0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('date_reviewed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'date_reviewed')
    # ### end Alembic commands ###
