"""empty message

Revision ID: d49a31d30f9f
Revises: 60051975b8df
Create Date: 2020-01-18 13:38:24.594854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49a31d30f9f'
down_revision = '60051975b8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('rsvp_accepted', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('rsvp_sent', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rsvp_sent')
    op.drop_column('applications', 'rsvp_accepted')
    # ### end Alembic commands ###
