"""empty message

Revision ID: f71a8e53aa0e
Revises: 60051975b8df
Create Date: 2020-01-18 16:11:13.709063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71a8e53aa0e'
down_revision = '60051975b8df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('decision_sent', sa.Boolean(), nullable=False))
    op.add_column('applications', sa.Column('rsvp_accepted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rsvp_accepted')
    op.drop_column('applications', 'decision_sent')
    # ### end Alembic commands ###
